CREATE TABLE USERS(
	ID VARCHAR(8) PRIMARY KEY,
	PASSWORD VARCHAR(8),
	NAME VARCHAR(20),
	ROLE VARCHAR(5)
);

INSERT INTO USERS
VALUES('test','1234','관리자','admin');

INSERT INTO USERS
VALUES('user1','1234','김그린','user');

DROP TABLE board;

CREATE TABLE BOARD(
	SEQ INT(5) PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(200),
	WRITER VARCHAR(20),
	CONTENT VARCHAR(2000),
	REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CNT INT(5) DEFAULT 0
);

INSERT INTO board(title, writer, content)
VALUES('가입인사','관리자','안뇨어엉');

COMMIT;

SELECT * FROM board WHERE seq=3;dept